import Head from 'next/head'
import React, { useRef, useEffect, useState } from 'react';
import Logo from '../components/logo'
import Settings from '../components/settings';
import Image from 'next/image';

// Mapbox
import mapboxgl from '!mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

export default function Home() {
  mapboxgl.accessToken = 'pk.eyJ1IjoiZ3Vuc29kbyIsImEiOiJja282bHRrYmYwd3d5MnhteTU0eWZqNjJnIn0.9vEapIZT5ijllLtYQaLhzw';

  const mapContainer = useRef(null);
  const map = useRef(null);
  const [lng, setLng] = useState(0);
  const [lat, setLat] = useState(0);
  const [zoom, setZoom] = useState(15);

  useEffect(() => {
    if (!navigator.geolocation) {
      console.log("No navigator found");
    } else {
      navigator.geolocation.getCurrentPosition((position) => {
        setLat(position.coords.latitude);
        setLng(position.coords.longitude);

        map.current = new mapboxgl.Map({
          container: mapContainer.current,
          style: 'mapbox://styles/mapbox/streets-v11',
          center: [position.coords.longitude, position.coords.latitude],
          zoom: zoom
        });
      }, () => {
        console.log('Unable to retrieve your location');
      });
    }
  }, []);

  // useEffect(() => {
  //   map.current.flyTo({
  //     center: [lng, lat]
  //   })
  // }, [lng, lat])

  return (
    <div>
      <Head>
        <title>Find My Bike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo />
      <Settings />
      <main className='w-screen h-screen'>
        <div id='map' className='map-container w-full h-full z-0' ref={mapContainer}/>
        <div className='fixed bottom-0 right-0 h-56 w-full sm:w-[36rem] z-0 p-6 transition-width duration-500'>
          <div className='flex justify-center items-center w-full h-full bg-white rounded-2xl drop-shadow-lg transition'>
            <div className='grid grid-cols-5 gap-4 h-full w-full p-4'>
              <div className='relative col-span-2'>
                <Image src='/bike.png' layout='fill' objectFit='contain' />
              </div>
              <div className='flex flex-col col-span-3 mr-4 justify-center space-y-3'>
                <div>
                  <p className='font-bold text-2xl mb-2'>Main Bicycle</p>
                  <p className='text-sm'>Last moved: 12 minutes ago</p>
                  <p className='text-sm'>590 meters away from me</p>
                </div>
                <div className='grid grid-cols-2 gap-2'>
                  <button className='bg-blue-600 hover:bg-blue-800 text-white font-medium rounded-md p-1'>Light</button>
                  <button className='bg-blue-600 hover:bg-blue-800 text-white font-medium rounded-md p-1'>Sound</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
